import AppModel from "@model/AppModel";
//
import React from 'react';
import { JSX } from "react";

import { Box, Stack } from "@mui/material";

import { AiGen, Media, PatchAsset } from '@repo/api';
import { RestfulService } from '@repo/endpoint';

import DialogWindow from '@widgets/core/DialogWindow';
import TextInput    from '@widgets/core/TextInput';
import TagInput     from '@widgets/core/TagInput';

//
// AiGenSaveDialog — name + tag a freshly-generated asset before keeping it in the library. The asset already
// exists (source.origin = generated); this sets its display name + tags (PatchAsset). The parent owns
// open/close + the generated result and handles Discard (delete). Owns its own form state.
//
export function AiGenSaveDialog( props : AiGenSaveDialog.Props ) : JSX.Element
{
    const appmodel : AppModel = AppModel.instance();

    const [name,setName] = React.useState< string >( props.defaultName );
    const [tags,setTags] = React.useState< Array<string> >( [] );

    ////////////////////////////////////////////////////////////////////////////////////////////
    // persist name + tags on the generated asset → true on success (dialog closes)
    async function onSave() : Promise<boolean>
    {
        if( name.trim() === "" ) return false;
        const reply : RestfulService.Reply<PatchAsset.Response> = await appmodel.server.fetch(
            new PatchAsset( props.candidate.guid, { name: name.trim(), tags } ) );
        return props.onSaved( reply.ok );
    }

    ////////////////////////////////////////////////////////////////////////////////////////////
    // preview the generated bytes (image → thumbnail, audio → player)
    function preview() : JSX.Element | null
    {
        if( props.candidate.kind === Media.Kind.IMAGE )
            return <Box component="img" src={ props.candidate.previewUrl } alt="preview"
                        sx={{ width: "100%", maxHeight: 260, objectFit: "contain", borderRadius: 1, bgcolor: "action.hover" }} />;
        if( props.candidate.kind === Media.Kind.AUDIO )
            return <Box component="audio" src={ props.candidate.previewUrl } controls sx={{ width: "100%" }} />;
        return null;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////
    return  <DialogWindow id="ai-gen-save"
                          title={"Save to library"}
                          yesLabel={"Save"}
                          cancelLabel={"Cancel"}
                          minWidth="sm"
                          ready={ name.trim() !== "" }
                          onYes={ onSave }
                          onClose={ props.onClose }>
                <Stack spacing={ 2 } sx={{ p: 2 }}>
                    { preview() }
                    <TextInput id="ai-gen-name" label={"Name"} value={ name } maxLength={ 300 } onChange={ setName } sx={{ width: "100%" }} />
                    <TagInput id="ai-gen-tags" label={"Tags"} value={ tags } choices={ [] } onChange={ setTags } />
                </Stack>
            </DialogWindow>;
}

export namespace AiGenSaveDialog
{
    export interface Props
    {
        candidate   : AiGen.Candidate;
        defaultName : string;
        onSaved     : ( ok : boolean ) => boolean;   // report result to parent; return true to close
        onClose     : () => void;
    }
}

export default AiGenSaveDialog;
// eof
